[package]
name = "matmul"
version = "0.1.0"
edition = "2021"

[dependencies]
rayon = "1.5"
ndarray = { version = "0.16.1", features = ["rayon"] }
blas-src = { version = "0.10.0", features = ["accelerate"] }
cblas = "0.4.0"

